//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public bool IsOfAge { get; set; }
        public string emailAddress { get; set; }
        public int dbkey { get; set; }
    }
}
