//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drink
    {
        public string Name { get; set; }
        public string Brand { get; set; }
        public Nullable<short> Year { get; set; }
        public string SKU { get; set; }
    }
}
