//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testPOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int orderNumber { get; set; }
        public string CustomerName { get; set; }
        public decimal Price { get; set; }
    }
}
