insert into dbo.Products ([ProductName], [ProductPrice], [ProductCategory], [ProductBrand], [ingredient_1], [ingredient_2], [ingredient_3], [ingredient_4], [ingredient_5], [ingredient_6], [ingredient_7]) 
VALUES ('Classic Manhattan', CAST(12.0000 AS Decimal(19, 4)), 1, 'Whiskey', 'Evan Williams', 'Sweet Vermouth', 'Angostura', 'Cherry Garnish', NULL, NULL, NULL)
insert into dbo.Products ([ProductName], [ProductPrice], [ProductCategory], [ProductBrand], [ingredient_1], [ingredient_2], [ingredient_3], [ingredient_4], [ingredient_5], [ingredient_6], [ingredient_7]) 
VALUES ('Blanc Check', CAST(9.0000 AS Decimal(19, 4)), 1, 'Whiskey', 'Sazerac ', 'Lillet Blanc', 'Sweet Vermouth', 'Lavendar Bitters', NULL, NULL, NULL)
insert into dbo.Products ([ProductName], [ProductPrice], [ProductCategory], [ProductBrand], [ingredient_1], [ingredient_2], [ingredient_3], [ingredient_4], [ingredient_5], [ingredient_6], [ingredient_7]) 
VALUES ('Brooklyn', CAST(8.0000 AS Decimal(19, 4)), 1, 'Rye Whiskey', 'Wild Turkey Rye', 'Dry Vermouth', 'Sweet Vermouth', 'Orange Bitters', NULL, NULL, NULL)
insert into dbo.Products ([ProductName], [ProductPrice], [ProductCategory], [ProductBrand], [ingredient_1], [ingredient_2], [ingredient_3], [ingredient_4], [ingredient_5], [ingredient_6], [ingredient_7]) 
VALUES ('Up State', CAST(10.0000 AS Decimal(19, 4)), 1, 'Rye Whiskey', 'Rittenhouse Rye', 'Sweet Vermouth', 'Orange Bitters', NULL, NULL, NULL, NULL)
insert into dbo.Products ([ProductName], [ProductPrice], [ProductCategory], [ProductBrand], [ingredient_1], [ingredient_2], [ingredient_3], [ingredient_4], [ingredient_5], [ingredient_6], [ingredient_7]) 
VALUES ('Contessa', CAST(9.0000 AS Decimal(19, 4)), 1, 'Gin', 'Madam Pattrini', 'Dry Vermouth', 'Aperol', 'Lemon Garnish', NULL, NULL, NULL)
insert into dbo.Products ([ProductName], [ProductPrice], [ProductCategory], [ProductBrand], [ingredient_1], [ingredient_2], [ingredient_3], [ingredient_4], [ingredient_5], [ingredient_6], [ingredient_7]) 
VALUES ('Endless Summer', CAST(9.0000 AS Decimal(19, 4)), 1, 'Gin', 'Tanqueray', 'Sweet Vermouth', 'Campari', 'Pineapple', 'OJ', NULL, NULL)
insert into dbo.Products ([ProductName], [ProductPrice], [ProductCategory], [ProductBrand], [ingredient_1], [ingredient_2], [ingredient_3], [ingredient_4], [ingredient_5], [ingredient_6], [ingredient_7]) 
VALUES ('Cablegram', CAST(8.0000 AS Decimal(19, 4)), 1, 'Whiskey', '1792 Small Batch', 'Lemon', 'Simple', 'Crabbies', NULL, NULL, NULL)
insert into dbo.Products ([ProductName], [ProductPrice], [ProductCategory], [ProductBrand], [ingredient_1], [ingredient_2], [ingredient_3], [ingredient_4], [ingredient_5], [ingredient_6], [ingredient_7]) 
VALUES ('Bourbon and Elder', CAST(9.0000 AS Decimal(19, 4)), 1, 'Whiskey', 'Buffalo Trace', 'St.Germain', 'Bitters', NULL, NULL, NULL, NULL)
insert into dbo.Products ([ProductName], [ProductPrice], [ProductCategory], [ProductBrand], [ingredient_1], [ingredient_2], [ingredient_3], [ingredient_4], [ingredient_5], [ingredient_6], [ingredient_7]) 
VALUES ('Red Devil ', CAST(9.0000 AS Decimal(19, 4)), 1, 'Whiskey', 'Wild Turkey', 'Aperol', 'Blackerry Brandy', 'Grapefruit', NULL, NULL, NULL)
insert into dbo.Products ([ProductName], [ProductPrice], [ProductCategory], [ProductBrand], [ingredient_1], [ingredient_2], [ingredient_3], [ingredient_4], [ingredient_5], [ingredient_6], [ingredient_7]) 
VALUES ('Black Thorne', CAST(8.0000 AS Decimal(19, 4)), 1, 'Whiskey', 'Jameson', 'Sweet Vermouth', 'Bitters', 'Absinthe wash', NULL, NULL, NULL)
insert into dbo.Products ([ProductName], [ProductPrice], [ProductCategory], [ProductBrand], [ingredient_1], [ingredient_2], [ingredient_3], [ingredient_4], [ingredient_5], [ingredient_6], [ingredient_7]) 
VALUES ('The Margarita', CAST(8.0000 AS Decimal(19, 4)), 1, 'Tequila', 'Hornitos Plata', 'Gran Gala', 'Honey', 'Lime', 'OJ', NULL, NULL)
insert into dbo.Products ([ProductName], [ProductPrice], [ProductCategory], [ProductBrand], [ingredient_1], [ingredient_2], [ingredient_3], [ingredient_4], [ingredient_5], [ingredient_6], [ingredient_7]) 
VALUES ('Hemingway Daiquiri', CAST(8.0000 AS Decimal(19, 4)), 1, 'Rum', 'Bacardi Silver', 'Luxardo', 'Sour', 'Grapefruit', NULL, NULL, NULL)
insert into dbo.Products ([ProductName], [ProductPrice], [ProductCategory], [ProductBrand], [ingredient_1], [ingredient_2], [ingredient_3], [ingredient_4], [ingredient_5], [ingredient_6], [ingredient_7]) 
VALUES ('Weeski', CAST(10.0000 AS Decimal(19, 4)), 1, 'Whiskey', 'Tullamore Dew', 'Lillet Blanc', 'Triple Sec', 'Orange Bitters', NULL, NULL, NULL)
insert into dbo.Products ([ProductName], [ProductPrice], [ProductCategory], [ProductBrand], [ingredient_1], [ingredient_2], [ingredient_3], [ingredient_4], [ingredient_5], [ingredient_6], [ingredient_7]) 
VALUES ('Ramos Fizz', CAST(9.0000 AS Decimal(19, 4)), 1, 'Gin', 'Sour', 'Cream ', 'Egg White', NULL, NULL, NULL, NULL)
insert into dbo.Products ([ProductName], [ProductPrice], [ProductCategory], [ProductBrand], [ingredient_1], [ingredient_2], [ingredient_3], [ingredient_4], [ingredient_5], [ingredient_6], [ingredient_7]) 
VALUES ('Juicy Pear', CAST(9.0000 AS Decimal(19, 4)), 1, 'Vodka', 'Absolut Pear', 'Lemon', 'Simple', NULL, NULL, NULL, NULL)
insert into dbo.Products ([ProductName], [ProductPrice], [ProductCategory], [ProductBrand], [ingredient_1], [ingredient_2], [ingredient_3], [ingredient_4], [ingredient_5], [ingredient_6], [ingredient_7]) 
VALUES ('Juicy Lucy', CAST(10.0000 AS Decimal(19, 4)), 2, 'Sandwhich', 'Grass Fed Angus Beef', NULL, NULL, NULL, NULL, NULL, NULL)
insert into dbo.Products ([ProductName], [ProductPrice], [ProductCategory], [ProductBrand], [ingredient_1], [ingredient_2], [ingredient_3], [ingredient_4], [ingredient_5], [ingredient_6], [ingredient_7]) 
VALUES ('Mac n Cheese', CAST(10.0000 AS Decimal(19, 4)), 2, 'Plate', 'Macaroni', NULL, NULL, NULL, NULL, NULL, NULL)
insert into dbo.Products ([ProductName], [ProductPrice], [ProductCategory], [ProductBrand], [ingredient_1], [ingredient_2], [ingredient_3], [ingredient_4], [ingredient_5], [ingredient_6], [ingredient_7]) 
VALUES ('Steak n Frittes', CAST(12.0000 AS Decimal(19, 4)), 2, 'Entray', '10oz Free Range Steak', NULL, NULL, NULL, NULL, NULL, NULL)

INSERT INTO dbo.Users ([UserID], [Username], [Password], [AccessLevel])
VALUES (666, 666, 666, 666)
INSERT INTO dbo.Users ([UserID], [Username], [Password], [AccessLevel])
VALUES (1, 420, 420, 1)
INSERT INTO dbo.Users ([UserID], [Username], [Password], [AccessLevel])
VALUES (2, 69, 69, 0)