//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public decimal ProductPrice { get; set; }
        public int ProductCategory { get; set; }
        public Nullable<int> ProductYear { get; set; }
        public string ProductBrand { get; set; }
        public string ingredient_1 { get; set; }
        public string ingredient_2 { get; set; }
        public string ingredient_3 { get; set; }
        public string ingredient_4 { get; set; }
        public string ingredient_5 { get; set; }
        public string ingredient_6 { get; set; }
        public string ingredient_7 { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
    }
}
